# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rmjHmfyQTjcCwDjzmBD4AwHjY2dKeAPi
"""

import sys
import tweepy
import csv

#pass security information to variables
consumer_key="5QKampPkKioPJcx3xW7jG3X5s"
consumer_secret="NAoueL0lVTZ2MauQ0aGTG3yhn4NPWX5XaUdhk9Acfha4FkYyzp"
access_key = "2285912300-TJ5U2NVZuuekRwrkfwKDJqpXmNBLcACE2CBnTf5"
access_secret = "JmXSScoMZPFS1FpONhfErBRLRizPk4DmbnnNYvN3oMot6"


#use variables to access twitter
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_key, access_secret)
api = tweepy.API(auth)

#create an object called 'customStreamListener'

class CustomStreamListener(tweepy.StreamListener):

    def on_status(self, status):
        print (status.author.screen_name, status.created_at, status.text)
        # Writing status data
        with open('OutputStreaming.txt', 'a') as f:
            writer = csv.writer(f)
            writer.writerow([status.text])


    def on_error(self, status_code):
        print >> sys.stderr, 'Encountered error with status code:', status_code
        return True # Don't kill the stream

    def on_timeout(self):
        print >> sys.stderr, 'Timeout...'
        return True # Don't kill the stream

# Writing csv titles
with open('OutputStreaming.txt', 'w') as f:
    writer = csv.writer(f)
    writer.writerow(['Text'])

streamingAPI = tweepy.streaming.Stream(auth, CustomStreamListener())
streamingAPI.filter(track=['starbucks'])